### ISSUE TITLE
MCHV repository: Missing tdlight-natives-linux-armhf

### ISSUE THREAD

**Issue by Luciferino90** [tdlight-team/tdlight-java-natives#5]
Hi
I was updating my software from tdlight-java-bom:2.8.5.8 to tdlight-java-bom:2.8.10.4 upgrading from and tdlight-natives-*:4.0.274 to 4.0.299.

It seems that tdlight-natives-linux-armhf are gone from your repository, is it wanted?

Thanks

**Comment by cavallium** [comment]
I just noticed it. I'll fix it this week

**Comment by cavallium** [comment]
I added them, the next release will contain the armhf library
