### ISSUE TITLE
build_linux_amd64_ssl1.sh error

### ISSUE THREAD

**Issue by prog-ape** [tdlight-team/tdlight-java-natives#6]
I am running build_linux_amd64_ssl1.sh directly, how to solve this kind of error, what needs to be modified, the environment is centos 8, java11

+ REVISION=1.0.0.0-SNAPSHOT
+ rm -rf implementations/tdlight/td_tools_build implementations/tdlight/build api/target-legacy api/target api/.ci-friendly-pom.xml implementations/tdlight/td/generate/auto natives/src/main/java/it/tdlight/jni natives/build natives/tdjni_bin natives/tdjni_docs
+ mkdir -p implementations/tdlight/build implementations/tdlight/build/td_bin/bin implementations/tdlight/td_tools_build/java/it/tdlight/jni api/src/main/java-legacy/it/tdlight/jni api/src/main/java-sealed/it/tdlight/jni natives/src/main/java/it/tdlight/jni natives/build natives/tdjni_bin natives/tdjni_docs
+ HOST_CMAKE_C_COMPILER=/usr/bin/clang-12
+ HOST_CMAKE_CXX_COMPILER=/usr/bin/clang++-12
+ HOST_CMAKE_C_FLAGS=-fuse-ld=lld
+ HOST_CMAKE_CXX_FLAGS='-fuse-ld=lld -stdlib=libc++'
+ HOST_CMAKE_EXE_LINKER_FLAGS='-lc++ -lc++abi -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind'
+ export 'CMAKE_CXX_FLAGS= -std=c++14'
+ CMAKE_CXX_FLAGS=' -std=c++14'
++ which sccache
++ alias
++ eval declare -f
+++ declare -f
++ /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot sccache
+ CCACHE=/root/.cargo/bin/sccache
+ [[ -x /root/.cargo/bin/sccache ]]
+ echo 'found sccache: /root/.cargo/bin/sccache'
found sccache: /root/.cargo/bin/sccache
+ cd implementations/tdlight/td_tools_build
+ CXXFLAGS=-stdlib=libc++
+ CC=/usr/bin/clang-12
+ CXX=/usr/bin/clang++-12
+ cmake -DCMAKE_C_COMPILER=/usr/bin/clang-12 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-12 '-DCMAKE_C_FLAGS= -fuse-ld=lld' '-DCMAKE_CXX_FLAGS= -std=c++14 -fuse-ld=lld -stdlib=libc++' '-DCMAKE_EXE_LINKER_FLAGS= -lc++ -lc++abi -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind' -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=/root/.cargo/bin/sccache -DCMAKE_CXX_COMPILER_LAUNCHER=/root/.cargo/bin/sccache -DCMAKE_C_FLAGS_RELEASE= '-DCMAKE_CXX_FLAGS_RELEASE=-O0 -DNDEBUG' -DTD_ENABLE_LTO=OFF -DTD_ENABLE_JNI=ON ..
CMake Error: The source directory "/home/cent/tdlight-java-natives/.github/workflows/scripts/implementations/tdlight" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by cavallium** [comment]
you didn't clone the submodules

**Comment by prog-ape** [comment]
> you didn't clone the submodules

Which submodule is it? I cloned it in this way: git clone --recursive https://github.com/tdlight-team/tdlight-java-natives.git

**Comment by cavallium** [comment]
> > you didn't clone the submodules
> 
> Which submodule is it? I cloned it in this way: git clone --recursive https://github.com/tdlight-team/tdlight-java-natives.git

That's correct, in this way it works.

**Comment by cavallium** [comment]
By the way, why are you trying to build the natives? The new TDLight-java version already offers some built-in precompiled binaries for the most popular platforms.

**Comment by prog-ape** [comment]
> By the way, why are you trying to build the natives? The new TDLight-java version already offers some built-in precompiled binaries for the most popular platforms.

Because the GLIBC version of some servers is high or low, resulting in an error when starting, or the OpenSSL3 version must also be compatible with tdlight

**Comment by cavallium** [comment]
Yes, but now the precompiled binary with openssl1 is using ubuntu 20.04, so it should be compatible with any non-ancient server.

Why are you using the openssl3 tdlight binary? @levlam suggests to use openssl1 with tdlib if possible.
